### PR TITLE
Update newdoc templates to match upstream; other enhancements to newdoc

### PR DESCRIPTION
**Pull request by msuchane**
Resolves issue #18.

I've updated the templates bundled with newdoc to their current versions in the modular reference.

Some changes to the templates were necessary: mainly, I had to replace ID and title strings to be machine-processable. Additionally, I've kept the usage of parent context, which is different in the modular reference from what we've been using in RHEL. Feel free to compare the two sets of templates and ask for explanations if necessary.

This PR doesn't enable newdoc to use the upstream templates directly, downloading them from the modular reference repo on each run. I'm not even sure if that's desirable either to the modular reference maintainers (it would require adding the Python formatting variables to their templates) or to newdoc users (without testing, templates might break overnight).

Additionally, this PR adds various fixes and improvements to newdoc:

* New packaging mechanism, tito, which makes packaging easier for me.
* Documentation on building and distributing RPM and pip packages.
* Substitutions when creating the ID now catch more characters and undesirable syntax

### CODE REVIEW

**Comment by msuchane** [comment]
@jhradilek, this PR updates the templates that newdoc uses to align them with upstream. I'll distribute the updated packages as soon as this is merged.

**Comment by msuchane** [comment]
@rkratky or @VladimirSlavik, would you like to review this PR before I merge it?

**Comment by VladimirSlavik** [comment]
I don't see anything wrong.

**Comment by msuchane** [comment]
Oh, one more thing, actually. I've just noticed that the upstream templates have switched to using a dash (`-`) as the separator between the ID and `{context}`. My `newdoc` templates are still using an underscore (`_`) as is the habit in RHEL documentation.

Any opinions on whether `newdoc` should switch to dashes, too?

**Comment by rkratky** [comment]
> Oh, one more thing, actually. I've just noticed that the upstream templates have switched to using a dash (-) as the separator between the ID and {context}. My newdoc templates are still using an underscore (_) as is the habit in RHEL documentation.

WTF? Who changed it again? I thought the last consensus was to keep the underscore for parseability.

I vote for keeping the underscore in `newdoc`.

**Comment by rkratky** [comment]
Oh, and the PR LGTM.

**Comment by msuchane** [comment]
> WTF? Who changed it again? I thought the last consensus was to keep the underscore for parseability.

Well GitHub says that the files were last changed 6 months ago, so maybe that decision hasn't been reflected in them yet?

Anyway, thanks for the review. I'm going to merge the branch and update the packages.

**Comment by jhradilek** [comment]
It looks like the change was introduced with this commit, so definitely not a recent one: https://github.com/redhat-documentation/modular-docs/commit/18bef9b2bd89279d562cefae4cebfc02fb19c215

**Pull request merged**
