### PR TITLE
Add nebel utility

### PR DESCRIPTION
**Pull request by fbolton**
Contributing the nebel utility to the redhat-documentation/tools repo.

### CODE REVIEW

**Comment by fbolton** [comment]
Hi @ncbaratta ! This is the PR for contributing nebel to the redhat-documentation/tools repo.

**Comment by rkratky** [comment]
Excellent. Thanks, @fbolton.

I'd suggest you get in touch with @mrksu who developed [newdoc](https://github.com/redhat-documentation/tools/tree/master/newdoc), a script that seems to offer similar features.

**Review by rkratky — APPROVED** [review]

**Comment by fbolton** [comment]
Thanks, @rkratky !

**Comment by msuchane** [comment]
@fbolton, looking briefly at your utility, it does overlap with my `newdoc` in some use cases. We should definitely compare our projects and collaborate so that we don't reinvent the wheel unnecessarily :-)

I've noticed that `nebel` is written in Python 2.7. You might want to consider porting it to Python 3. In current Fedora releases, Python 2 is already being removed bit by bit, and Fedora 32 is planned to include only the basic Python 2.7 runtime with no other Python 2 packages.

**Comment by fbolton** [comment]
@mrksu The initial use case for nebel was to facilitate a workflow where we defined modules and assemblies as rows in a Google sheet and then used the sheet (exported as a CSV file) to generate assemblies and modules automatically. This has been useful for migrating legacy content. Since then, the functionality of nebel has expanded a bit.

Good point about Python 2.7. After Fedora 32 gets released sounds like it would be a good time to switch. It might be good to support both versions for a while (although I'm not sure if that's possible).

**Pull request merged**
